//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EndToEnd
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.Topics = new HashSet<Topic>();
        }
    
        public int CourseID { get; set; }
        [Display(Name = "Name")]
        [StringLength(20, ErrorMessage = "The name must be under 20 characters.")]
        public string CourseName { get; set; }
        [Display(Name = "Description")]
        [StringLength(20, ErrorMessage = "The description must be under 20 characters.")]
        public string CourseDescription { get; set; }
        public Nullable<int> CCID { get; set; }
    
        public virtual CC CC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Topic> Topics { get; set; }
    }
}
